# This is a config for E2B sandbox template.
# You can use template ID (xdwndg2guy5heudf5fck) or template name (vibe-nextjs-fazamttqn-007) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-fazamttqn-007") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-fazamttqn-007") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-fazamttqn-007')

team_id = "ac5f9856-8136-47e4-8fbf-70f28aae2ece"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-fazamttqn-007"
template_id = "xdwndg2guy5heudf5fck"
